name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy to VPS
      run: |
        sshpass -p ${{ secrets.VPS_PASSWORD }} rsync -avz -e 'ssh -o StrictHostKeyChecking=no' dist/ vishalds@${{ secrets.VPS_HOST }}:/home/vishalds/portal/
      env:
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}